services:
  - type: web
    name: courier-frontend
    runtime: static
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
